<?php

namespace Database\Seeders;

use App\Models\FraudKamusRisiko;
use Illuminate\Database\Seeder;

/**
 * Kamus Risiko Kecurangan — 165 butir Referensi MCP KPK 2025.
 *
 * Sumber: lembar "Referensi MCP 2025" pada Format Kertas Kerja FRA, dibangkitkan
 * langsung dari berkasnya (bukan diketik ulang) supaya tidak ada butir yang
 * hilang atau berubah kata.
 *
 * MCP (Monitoring Centre for Prevention) adalah pemantauan aksi pencegahan
 * korupsi oleh KPK yang bersumber dari Perpres No. 54 Tahun 2018 tentang
 * Strategi Nasional Pencegahan Korupsi. Ketiga belas areanya adalah area yang
 * dinilai KPK, sehingga daftar ini bukan sekadar contoh: ia daftar risiko yang
 * memang diperiksa.
 *
 * Idempoten — dijalankan ulang tidak menggandakan baris.
 */
class FraudKamusMcpSeeder extends Seeder
{
    private const SUMBER = 'MCP KPK 2025';

    public function run(): void
    {
        foreach (self::BUTIR as [$area, $nomor, $uraian]) {
            FraudKamusRisiko::updateOrCreate(
                ['sumber' => self::SUMBER, 'area' => $area, 'nomor' => $nomor],
                ['uraian' => $uraian, 'tahapan_proses' => null],
            );
        }
    }

    /** @var array<int, array{0: string, 1: int, 2: string}> */
    private const BUTIR = [
        ['PEMBERIAN HIBAH', 1, 'Kegiatan Hibah tidak didasari oleh kebutuhan penerima hibah'],
        ['PEMBERIAN HIBAH', 2, 'Calon penerima Hibah tidak mengajukan proposal sesuai ketentuan'],
        ['PEMBERIAN HIBAH', 3, 'Terdapat calon penerima Hibah yang fiktif'],
        ['PEMBERIAN HIBAH', 4, 'Calon penerima Hibah tidak sesuai dengan kriteria yang ditetapkan'],
        ['PEMBERIAN HIBAH', 5, 'Penyerahan Hibah bukan kepada pihak yang sudah ditetapkan dalam SK'],
        ['PEMBERIAN HIBAH', 6, 'Terjadi keterlambatan penyerahan Hibah'],
        ['PEMBERIAN HIBAH', 7, 'Terjadi pengurangan atas Hibah yang diserahkan'],
        ['PEMBERIAN HIBAH', 8, 'Terjadi pemungutan/pengenaan biaya kepada penerima Hibah'],
        ['PEMBERIAN HIBAH', 9, 'Terjadinyab penyimpangan dalam penggunaan dana Hibah'],
        ['PEMBERIAN HIBAH', 10, 'Terjadinya kesalahan/penyimpangan dalam pengenaan pajak'],
        ['PEMBERIAN HIBAH', 11, 'Penerima Hibah tidak mempertanggungjawabkan penggunaan bantuan Hibah'],
        ['PEMBERIAN HIBAH', 12, 'DST'],
        ['PEMBERIAN BANSOS', 1, 'Jenis bantuan tidak sesuai dengan kebutuhan individu/kelompok penerima bantuan sosial'],
        ['PEMBERIAN BANSOS', 2, 'Penyusunan Anggaran Kebutuhan PBJ tidak wajar (MARK UP)'],
        ['PEMBERIAN BANSOS', 3, 'Terdapat calon penerima Bansos yang fiktif'],
        ['PEMBERIAN BANSOS', 4, 'Penerima Bansos tidak sesuai dengan kriteria yang ditetapkan'],
        ['PEMBERIAN BANSOS', 5, 'Kesalahan dalam menetapkan spesifikasi barang Bansos'],
        ['PEMBERIAN BANSOS', 6, 'Keterlambatan pemenuhan alat bantu disabilitas'],
        ['PEMBERIAN BANSOS', 7, 'HPS tidak didukung oleh dokumentasi penyusunan HPS yang memadai'],
        ['PEMBERIAN BANSOS', 8, 'HPS disusun terlalu tinggi/mark up'],
        ['PEMBERIAN BANSOS', 9, 'HPS disusun terlalu rendah (diusulkan di hapus)'],
        ['PEMBERIAN BANSOS', 10, 'Substansi dalam dokumen pemilihan diarahkan untuk memenangkan calon penyedia tertentu'],
        ['PEMBERIAN BANSOS', 11, 'Adanya kelemahan/kesalahan dalam substansi kontrak yang merugikan pemerintah'],
        ['PEMBERIAN BANSOS', 12, 'Terjadinya persekongkolan dalam pemilihan penyedia (risiko saat PBJ)'],
        ['PEMBERIAN BANSOS', 13, 'Terjadinya kegagalan proses pemilihan penyedia'],
        ['PEMBERIAN BANSOS', 14, 'Terjadinya pekerjaan fiktif'],
        ['PEMBERIAN BANSOS', 15, 'Pelaksanaan pekerjaan mendahului kontrak/penandatangan SPPBJ (diusulkan di hapus karena e-purchasing)'],
        ['PEMBERIAN BANSOS', 16, 'Pekerjaan bukan dilaksanakan oleh rekanan pemenang'],
        ['PEMBERIAN BANSOS', 17, 'Keterlambatan penyelesaiaan pekerjaan'],
        ['PEMBERIAN BANSOS', 18, 'Rekanan tidak mengerjakan sesuai spesifikasi yang ditetapkan dalam kontrak'],
        ['PEMBERIAN BANSOS', 19, 'Terjadinya adendum pekerjaan yang tidak sesuai ketentuan'],
        ['PEMBERIAN BANSOS', 20, 'Terjadinya forcemajor'],
        ['PEMBERIAN BANSOS', 21, 'Pihak penyedia melakukan wanprestasi'],
        ['PEMBERIAN BANSOS', 22, 'Terjadinya hak2 penyedia yang tidak dipenuhi oleh PPK/PA/Perangkat Daerah'],
        ['PEMBERIAN BANSOS', 23, 'Terjadinya denda keterlambatan yang tidak dipungut dan disetor ke kas negara/daerah'],
        ['PEMBERIAN BANSOS', 24, 'Terjadinya kesalahan/penyimpangan dalam pengenaan pajak'],
        ['PEMBERIAN BANSOS', 25, 'Terjadinya pajak yang sudah dipungut/dipotong tapi tidak/belum disetor'],
        ['PEMBERIAN BANSOS', 26, 'Penyerahan Bansos bukan kepada pihak yang sudah ditetapkan'],
        ['PEMBERIAN BANSOS', 27, 'Terjadi keterlambatan penyerahan Bansos'],
        ['PEMBERIAN BANSOS', 28, 'Terjadi pengurangan atas Bansos yang diserahkan'],
        ['PEMBERIAN BANSOS', 29, 'Terjadi pemungutan/pengenaan biaya kepada penerima Bansos (diusulkan dihapus)'],
        ['PEMBERIAN BANSOS', 30, 'Penyimpangan penggunaan dana Bansos oleh pihak penerima (diusulkan dihapus)'],
        ['PEMBERIAN BANSOS', 31, 'DST'],
        ['PBJ (DPUPR, DINKES, DISDIK, ARPUSDA)', 1, 'Penyusunan Anggaran Kebutuhan PBJ tidak wajar'],
        ['PBJ (DPUPR, DINKES, DISDIK, ARPUSDA)', 2, 'Rencana Pengadaan barang/jasa bukan berdasarkan kebutuhan/usulan pihak pengguna (user)'],
        ['PBJ (DPUPR, DINKES, DISDIK, ARPUSDA)', 3, 'Spesifikasi barang/jasa yang akan diadakan tidak sesuai kebutuhan user'],
        ['PBJ (DPUPR, DINKES, DISDIK, ARPUSDA)', 4, 'HPS tidak didukung oleh dokumentasi penyusunan HPS yang memadai'],
        ['PBJ (DPUPR, DINKES, DISDIK, ARPUSDA)', 5, 'HPS disusun terlalu tinggi/mark up'],
        ['PBJ (DPUPR, DINKES, DISDIK, ARPUSDA)', 6, 'HPS disusun terlalu rendah (diusulkan di coret)'],
        ['PBJ (DPUPR, DINKES, DISDIK, ARPUSDA)', 7, 'Terjadinya persekongkolan dalam pemilihan penyedia (diusulkan di coret)'],
        ['PBJ (DPUPR, DINKES, DISDIK, ARPUSDA)', 8, 'Terjadinya kegagalan proses pemilihan penyedia (diusulkan dicoret)'],
        ['PBJ (DPUPR, DINKES, DISDIK, ARPUSDA)', 9, 'Terjadinya pekerjaan fiktif'],
        ['PBJ (DPUPR, DINKES, DISDIK, ARPUSDA)', 10, 'Adanya kelemahan/kesalahan dalam substansi kontrak yang merugikan pemerintah'],
        ['PBJ (DPUPR, DINKES, DISDIK, ARPUSDA)', 11, 'Pelaksanaan pekerjaan mendahului kontrak/penandatangan SPPBJ pada pengadaan langsung'],
        ['PBJ (DPUPR, DINKES, DISDIK, ARPUSDA)', 12, 'Pekerjaan bukan dilaksanakan oleh rekanan pemenang'],
        ['PBJ (DPUPR, DINKES, DISDIK, ARPUSDA)', 13, 'Keterlambatan penyelesaiaan pekerjaan'],
        ['PBJ (DPUPR, DINKES, DISDIK, ARPUSDA)', 14, 'Rekanan tidak mengerjakan sesuai spesifikasi yang ditetapkan dalam kontrak'],
        ['PBJ (DPUPR, DINKES, DISDIK, ARPUSDA)', 15, 'Terjadinya adendum pekerjaan yang tidak sesuai ketentuan'],
        ['PBJ (DPUPR, DINKES, DISDIK, ARPUSDA)', 16, 'Terjadinya forcemajor'],
        ['PBJ (DPUPR, DINKES, DISDIK, ARPUSDA)', 17, 'Pihak penyedia melakukan wanprestasi'],
        ['PBJ (DPUPR, DINKES, DISDIK, ARPUSDA)', 18, 'Terjadinya hak2 penyedia yang tidak dipenuhi oleh PPK/PA/Perangkat Daerah'],
        ['PBJ (DPUPR, DINKES, DISDIK, ARPUSDA)', 19, 'Terjadinya denda keterlambatan yang tidak dipungut dan disetor ke kas negara/daerah'],
        ['PBJ (DPUPR, DINKES, DISDIK, ARPUSDA)', 20, 'Terjadinya kesalahan/penyimpangan dalam pengenaan pajak'],
        ['PBJ (DPUPR, DINKES, DISDIK, ARPUSDA)', 21, 'Terjadinya pajak yang sudah dipungut/dipotong tapi tidak/belum disetor (diusulkan dihapus)'],
        ['PBJ (DPUPR, DINKES, DISDIK, ARPUSDA)', 22, 'Terdapat BMD hasil pengadaan yang belum diserahterimakan oleh PPK kepada PA'],
        ['PEMILIHAN PENYEDIA (UKPBJ)', 1, 'Dokumen PBJ yang disampaikan oleh PA/KPA/PPK ke UKPBJ tidak lengkap'],
        ['PEMILIHAN PENYEDIA (UKPBJ)', 2, 'HPS yang diupload nilainya terlalu tinggi'],
        ['PEMILIHAN PENYEDIA (UKPBJ)', 3, 'Persyaratan yang ditetapkan dalam dokumen pengadaan yang harus dipenuhi oleh calon penyedia terlalu tinggi'],
        ['PEMILIHAN PENYEDIA (UKPBJ)', 4, 'Pokja Pemilihan mengalami tekanan baik secara internal maupun external dalam proses pemilihan penyedia barang /jasa'],
        ['PEMILIHAN PENYEDIA (UKPBJ)', 5, 'Terjadinya gratifikasi/suap kepada Tim Pokja'],
        ['PEMILIHAN PENYEDIA (UKPBJ)', 6, 'Para calon penyedia tidak dapat mengakses sistem (SPSE)'],
        ['PEMILIHAN PENYEDIA (UKPBJ)', 7, 'Pokja Pemilihan salah dalam melakukan evaluasi'],
        ['PEMILIHAN PENYEDIA (UKPBJ)', 8, 'Terjadinya persekongkolan dalam pemilihan penyedia'],
        ['PEMILIHAN PENYEDIA (UKPBJ)', 9, 'Terjadinya perubahan jadwal pemilihan yang signifikan'],
        ['PEMILIHAN PENYEDIA (UKPBJ)', 10, 'Hasil pemilihan penyedia tidak disetujui oleh PA/KPA'],
        ['PEMILIHAN PENYEDIA (UKPBJ)', 11, 'Terdapat sanggah/sanggah banding dalam proses penyelia'],
        ['PEMILIHAN PENYEDIA (UKPBJ)', 12, 'Terjadinya gagal proses oleh penyedia'],
        ['PELAYANAN DUKCAPIL', 1, 'Terjadinya pengurusan oleh Calo/Perantara'],
        ['PELAYANAN DUKCAPIL', 2, 'Terjadinya pemungutan biaya pelayanan'],
        ['PELAYANAN DUKCAPIL', 3, 'Terjadinya suap kepada petugas pelayanan'],
        ['PELAYANAN DUKCAPIL', 4, 'Terjadinya kesalahan dalam inputing data'],
        ['PELAYANAN DUKCAPIL', 5, 'Terjadinya pelayanan yang tidak sesuai prosedur/SOP (Pelayanan Yg Mempersulit)'],
        ['PELAYANAN DUKCAPIL', 6, 'Terjadinya gratifikasi kepada petugas'],
        ['PELAYANAN DUKCAPIL', 7, 'Terjadinya kerusakan peralatan pendukung pelayanan'],
        ['PELAYANAN DUKCAPIL', 8, 'Terjadinya gangguan pada aliran listrik'],
        ['PELAYANAN DUKCAPIL', 9, 'Terjadinya gangguan pada jaringan internet'],
        ['PELAYANAN DUKCAPIL', 10, 'Dokumen yang diajukan oleh masyarakat kepada petugas pelayanan tidak sesuai yang dipersyaratkan'],
        ['PELAYANAN DUKCAPIL', 11, 'Kehabisan blanko e-ktp'],
        ['PELAYANAN PERIZINAN', 1, 'Terjadinya pengurusan oleh Calo/Perantara'],
        ['PELAYANAN PERIZINAN', 2, 'Terjadinya pemungutan biaya pelayanan yang tidak sesuai ketentuan (diusulkan dihapus)'],
        ['PELAYANAN PERIZINAN', 3, 'Terjadinya kesalahan dalam inputing data'],
        ['PELAYANAN PERIZINAN', 4, 'Terjadinya pelayanan yang tidak sesuai prosedur/SOP (Pelayanan Yg Mempersulit)'],
        ['PELAYANAN PERIZINAN', 5, 'Terjadinya gratifikasi kepada petugas'],
        ['PELAYANAN PERIZINAN', 6, 'Ketidakstabilan aplikasi/sistem'],
        ['PELAYANAN PERIZINAN', 7, 'Terjadinya kerusakan peralatan pendukung pelayanan'],
        ['PELAYANAN PERIZINAN', 8, 'Terjadinya gangguan pada aliran listrik'],
        ['PELAYANAN PERIZINAN', 9, 'Terjadinya gangguan pada jaringan internet'],
        ['PELAYANAN PERIZINAN', 10, 'Dokumen yang diajukan oleh masyarakat kepada petugas pelayanan tidak sesuai yang dipersyaratkan'],
        ['PELAYANAN PERIZINAN', 11, 'Sosialisasi kemudahan pelayanan tidak tepat sasaran'],
        ['PERENCANAAN PEMBANGUNAN', 1, 'Adanya benturan kepentingan'],
        ['PERENCANAAN PEMBANGUNAN', 2, 'Proses perncanaan pembangunan diintervensi oleh pihak tertentu'],
        ['PERENCANAAN PEMBANGUNAN', 3, 'Terjadinya suap/gratifikasi'],
        ['PERENCANAAN PEMBANGUNAN', 4, 'Program dan kegiatan dipaksanakan untuk dilaksanakan walaupun tidak sesuai dengan RPJMD dan/atau Renstra OPD'],
        ['PERENCANAAN PEMBANGUNAN', 5, 'Pokok pikiran disampaikan di luar batas waktu yang telah ditentukan'],
        ['PERENCANAAN PEMBANGUNAN', 6, 'Pokok pikiran dipaksanakan untuk diajukan padahal tidak selaras dengan RPJMD dan/atau Renstra OPD'],
        ['PERENCANAAN PEMBANGUNAN', 7, 'Ketidaklengkapan dan ketidakakuratan data dan informasi pembangunan yang disediakan oleh OPD'],
        ['PERENCANAAN PEMBANGUNAN', 8, 'Ketidakselarasan antara dokumen perencanaan dengan dokumen lainnya seperti RTRW'],
        ['PERENCANAAN PEMBANGUNAN', 9, 'Hasil evaluasi tidak digunakan dalam dasar perencanaan'],
        ['PERENCANAAN PEMBANGUNAN', 10, 'Perubahan kebijakan regulasi yang mendadak'],
        ['PERENCANAAN PEMBANGUNAN', 11, 'Terdapat gangguan sistem aplikasi'],
        ['PERENCANAAN PEMBANGUNAN', 12, 'Ketidakpatuhan PD terhadap SOP penyusunan dokumen perencanaan'],
        ['PERENCANAAN PEMBANGUNAN', 13, 'Ketidakjelasan tanggungjawab dalam tim perencanaan di Bapperida'],
        ['PENYUSUNAN DAN IMPLEMENTASI ANGGARAN', 1, 'Proses penyusunan anggaran tidak sesuai dengan ketentuan/regulasi, khususnya ketika pedoman dari Kemendagri dan informasi dana transfer terlambat diterima'],
        ['PENYUSUNAN DAN IMPLEMENTASI ANGGARAN', 2, 'Terjadinya pemerasan oleh pihak tertentu dalam proses penyusunan anggaran (diusulkan dihapus)'],
        ['PENYUSUNAN DAN IMPLEMENTASI ANGGARAN', 3, 'SSH & ASB disusun tidak sesuai dengan ketentuan/regulasi'],
        ['PENYUSUNAN DAN IMPLEMENTASI ANGGARAN', 4, 'Markup SSH dan ASB'],
        ['PENYUSUNAN DAN IMPLEMENTASI ANGGARAN', 5, 'Terjadinya gratifikasi/suap kepada Penyusun dokumen anggaran, khususnya SSH/ASB'],
        ['PENYUSUNAN DAN IMPLEMENTASI ANGGARAN', 6, 'Adanya benturan kepentingan'],
        ['PENYUSUNAN DAN IMPLEMENTASI ANGGARAN', 7, 'Adanya intervensi pihak tertentu'],
        ['PENYUSUNAN DAN IMPLEMENTASI ANGGARAN', 8, 'Terjadinya keterlambatan dalam penyusunan dokumen perencanaan antara lain disebabkan keterlambatan hasil evaluasi Gubernur dan pembahasan angaran tidak segera mencapai kesepakatan'],
        ['PENYUSUNAN DAN IMPLEMENTASI ANGGARAN', 9, 'Adanya penetapan penyedia sbg pelaksana pekerjaan'],
        ['PENYUSUNAN DAN IMPLEMENTASI ANGGARAN', 10, 'Perjalanan Dinas Fiktif'],
        ['PENYUSUNAN DAN IMPLEMENTASI ANGGARAN', 11, 'Honorarium fiktif (diusulkan dihapus)'],
        ['PENYUSUNAN DAN IMPLEMENTASI ANGGARAN', 12, 'SIPD sulit diakses'],
        ['PENYUSUNAN DAN IMPLEMENTASI ANGGARAN', 13, 'Proses pengusulan anggaran oleh OPD tidak sesuai dengan kebutuhan'],
        ['MANAJEMEN ASN', 1, 'Terjadinya gratifikasi dalam proses pengelolaan ASN'],
        ['MANAJEMEN ASN', 2, 'Adanya intervensi pihak tertentu dalam Pengelolaan ASN, terutama dalam proses penempatan dan promosi'],
        ['MANAJEMEN ASN', 3, 'Adanya pembiaran atas pelanggaran disiplin ASN (diusulkan dihapus)'],
        ['MANAJEMEN ASN', 4, 'Pengangkatan/Promosi tidak sesuai ketentuan (diusulkan dihapus)'],
        ['MANAJEMEN ASN', 5, 'Kurangnya kelengkapan berkas oleh pegawai'],
        ['MANAJEMEN ASN', 6, 'Ketidaksesuaian data ASN dengan simpeg karena tidak update data'],
        ['PENGELOLAAN BMD', 1, 'Setelah melakukan pengadaan barang, BMD tidak dicatatkan sebagai aset milik pemerintah daerah dan tidak dilakukan pengamanan hukum melalui sertifikasi BMD (terutama untuk BMD tanah).'],
        ['PENGELOLAAN BMD', 2, 'Proses sertifikasi BMD tidak didukung dengan anggaran yang memadai, bahkan proses sertifikasi juga dinilai berbelit-belit.'],
        ['PENGELOLAAN BMD', 3, 'BMD disalahgunakan oleh beberapa oknum ASN, BMD tidak dikembalikan setelah selesai menjabat atau BMD dikembalikan dalam keadaan rusak sehingga tidak dapat dimanfaatkan.'],
        ['PENGELOLAAN BMD', 4, 'Pemanfaatan BMD tidak dilakukan penghitungan sesuai dengan nilai yang seharusnya.'],
        ['PENGELOLAAN BMD', 5, 'Pengguna kendaraan dinas tidak membayar pajak tepat waktu'],
        ['PENGELOLAAN BMD', 6, 'Pembayaran pajak kendaraan dinas tidak sesuai ketentuan'],
        ['PENGELOLAAN BMD', 7, 'Proses TGR tidak sesuai ketentuan peraturan perundang2an dan pihak yang terkena TGR tidak kooperatif'],
        ['OPTIMALISASI PAJAK/RETRIBUSI DAERAH', 1, 'Database pajak dan retribusi yang tidak di mutakhirkan secara berkala, sehingga potensi penerimaan pajak dan retribusi tidak terpetakan dengan baik;'],
        ['OPTIMALISASI PAJAK/RETRIBUSI DAERAH', 2, 'Nilai dasar pengenaan pengenaan pajak dan retribusi tidak dievaluasi secara berkala berdasarkan data terkini'],
        ['OPTIMALISASI PAJAK/RETRIBUSI DAERAH', 3, 'Penetapan potensi penerimaan pajak dan retribusi daerah dilakukan dengan tidak optimal sehingga mengurangi potensi penerimaan pemda;'],
        ['OPTIMALISASI PAJAK/RETRIBUSI DAERAH', 4, 'Pengendalian dan pengawasan pajak dan retribusi daerah tidak dilakukan sehingga mengakibatkan rendahnya kepatuhan pembayaran pajak dan retribusi daerah;'],
        ['OPTIMALISASI PAJAK/RETRIBUSI DAERAH', 5, 'Kurangnya sosialisasi kepada wajib pajak atas kewajiban pelaporan dan pembayaran pajak dan retribusi daerah.'],
        ['OPTIMALISASI PAJAK/RETRIBUSI DAERAH', 6, 'Penerimaan pajak dan retribusi tidak seluruhnya disetorkan ke kas daerah dan masuk dalam kantong pribadi petugas pajak. Dalam hal ini modus yang sering dilakukan adalah pembayaran pajak dan retribusi secara manual;'],
        ['OPTIMALISASI PAJAK/RETRIBUSI DAERAH', 7, 'Penyuapan/gratifikasi kepada pegawai Pemda agar pembayaran pajak dan retribusi dapat dikurangi dari pembayaran yang sesungguhnya;'],
        ['OPTIMALISASI PAJAK/RETRIBUSI DAERAH', 8, 'Penerimaan pajak tidak seluruhnya disetorkan ke kas daerah karena disembunyikan/tidak seluruhnya dilaporkan oleh Wajib Pajak;'],
        ['OPTIMALISASI PAJAK/RETRIBUSI DAERAH', 9, 'Pemeriksaan pajak kurang optimal karena ada WP tidak mau diperiksa dan menyembunyikan data usahanya'],
        ['OPTIMALISASI PAJAK/RETRIBUSI DAERAH', 10, 'Kurangnya kerjasama antar BPKPAD dengan Instansi (Satpol PP) terkait pemantauan dan penertiban objek pajak daerah seperti reklame dll'],
        ['OPTIMALISASI PAJAK/RETRIBUSI DAERAH', 11, 'Adanya kelompok di masyarakat yang menolak penegakan pajak daerah'],
        ['OPTIMALISASI PAJAK/RETRIBUSI DAERAH', 12, 'Belum optimalnya komunikasi petugas pajak dan retribusi dengan WP / WR karena pergantian personel'],
        ['OPTIMALISASI PAJAK/RETRIBUSI DAERAH', 13, 'Inovasi pelayanan utk pajak dan retribusi yang dikembangkan belum dimanfaatkan dengan baik oleh WP WR'],
        ['PELAYANAN PENDIDIKAN', 1, 'Terjadinya gratifikasi/suap dalam proses PPDB'],
        ['PELAYANAN PENDIDIKAN', 2, 'Adanya benturan kepentingan dalam proses PPDB dalam penentuan zonasi lingkungan'],
        ['PELAYANAN PENDIDIKAN', 3, 'Adanya intervensi pihak tertentu dalam Proses PPDB'],
        ['PELAYANAN PENDIDIKAN', 4, 'Terjadinya pemalsuan kelengkapan data calon siswa'],
        ['PELAYANAN PENDIDIKAN', 5, 'Penyalahgunaan penggunaan dana BOS'],
        ['PELAYANAN PENDIDIKAN', 6, 'Terjadinya gangguan jaringan listrik dan internet yang mempengaruhi proses PPDB on line (SMP)'],
        ['PELAYANAN PENDIDIKAN', 7, 'Adanya intervensi pihak tertentu dalam Proses Promosi dan mutasi tenaga pendidik dan kependidikan'],
        ['PELAYANAN KESEHATAN', 1, 'Terjadinya gratifikasi/suap dalam Pelayanan Kesehatan'],
        ['PELAYANAN KESEHATAN', 2, 'Terjadinya pelayanan yg tidak sesuai ketentuan (SOP)'],
        ['PELAYANAN KESEHATAN', 3, 'Pengajuan klaim biaya BPJS fiktif'],
        ['PELAYANAN KESEHATAN', 4, 'Mark up coding (kode pembiayaan)'],
        ['PELAYANAN KESEHATAN', 5, 'Penyalahgunaan identitas pasien asuransi orang lain'],
        ['PELAYANAN KESEHATAN', 6, 'Faskes tetap menjalankan operasional meski perizinan habis'],
        ['PELAYANAN KESEHATAN', 7, 'Pemalsuan SIP Tenaga kesehatan'],
    ];
}
